#!/usr/bin/env bash

DIR="/Users/selkamand/projects/r_packages/utilitybeltkraken/inst/testfiles"
Rscript kraken_extract_reads \
 --kreport_path $DIR/e_coli_l_monocytogones_s_enterica_50seqs_each.minikraken8GB.kreport \
 --kraken_stdout_path $DIR/e_coli_l_monocytogones_s_enterica_50seqs_each.minikraken8GB.stdout \
 --kraken_input_seqs $DIR/e_coli_l_monocytogones_s_enterica_50seqs_each.fasta \
 --kraken_input_seqs2 $DIR/e_coli_l_monocytogones_s_enterica_50seqs_each.fasta \
 --outfile_prefix "test" \
 --taxid 561 \
 --include_children
